meas_variance: .1      # Lateral position variance, meters
p_detection: .98         # Probability that an object will yield a detection
clutter_density:  .001 # Number of false detections expected in sensor range