# Initial state estimate
x0: 
    # Define weighted Gaussian Mixture components of the initial state estimate
    - {weight: 0.35, mu: [1.0, 1.0, 0.25, 0.25], sigma: [0.25, 0.25, .025, .025]}
    - {weight: 1.0, mu: [1.0, 0.0, 0.25, 0.0], sigma: [0.25, 0.25, .025, .025]}
    - {weight: 0.5, mu: [1.0, -1.0, 0.5, -0.5], sigma: [0.25, 0.25, .025, .025]}
    - {weight: 0.5, mu: [1.0, -2.0, 0.5, -0.25], sigma: [0.25, 0.25, .025, .025]}